- setup.py
Adapt minimal python version requirement and match classifiers.
> chore: update requirements

- cayennelpp/lpp_data.py
- cayennelpp/tests/test_lpp_data.py
Fixes some missed adaption and enhance debug messages.
> fix: add several small adaptions to lpp_data

- README.md
- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_frame.py
This adds extensive documenation to all classes, methods and functions.
Also a short example usage is added to the README. A small code enhancement
is shipped, too, i.e. adding an alias function to add barometer sensor data
by invoking existing add_pressure method.
Fixes #14
> docs: add docstrings and extend README

- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
Refine code based on codacy review, i.e. change assert. Also
rename attribute data to value in LppData.
> refactor: change handling of asserts

- README.md
by the following:
- add badges
- restructure text and add sections
> docs: enhance README.md

- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_frame.py
- cayennelpp/tests/test_lpp_type.py
Add test cases to achieve approx. 100% code coverage.
> tests: enhance coverage

- cayennelpp/lpp_data.py
Do not use or redefine builtin types for variables.
> fix: rename variable

- .gitignore
- cayennelpp/lpp_frame.py
- cayennelpp/tests/test_lpp_frame.py
Dear Sebastian,
this finally fixes the typo mentioned within #44.
With kind regards,
Andreas.
> Fix typo for "humidity"

- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_data.py
- cayennelpp/tests/test_lpp_frame.py
- cayennelpp/tests/test_lpp_type.py
- according to [IPSO](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) "load" Smart Object
- tested on hardware
> feat: Support Load

- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_data.py
- cayennelpp/tests/test_lpp_frame.py
- cayennelpp/tests/test_lpp_type.py
This is a rebase of #43 on top of the current master. Thanks @dolfandringa!
> feat: Add support for generic 4 byte unsigned integer

- README.md
- cayennelpp/tests/test_lpp_frame.py
cherry-picked commit from #52 to update Readme and tests. Added some more refinements on top.
> update readme and refine tests

- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_type.py
Contributions:
- minor refinements to documentation
- fixed names of attributes and parameters
- code deduplication in LppType
> refactor: code deduplication and refined documentation

- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/tests/test_lpp_data.py
- cayennelpp/tests/test_lpp_frame.py
This PR refines LppData and LppFrame size attributes and adds an (optional) max size attribute to LppFrame allowing to limit the bytes size of a frame.
> feat: add (optional) LppFrame max bytes size limit

- cayennelpp/lpp_data.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_data.py
- cayennelpp/tests/test_lpp_frame.py
- cayennelpp/tests/test_lpp_type.py
this refines the usage of LppType
> refactor: refine parsing and handling of LppType

- cayennelpp/lpp_frame.py
- cayennelpp/tests/test_lpp_frame.py
new function to filter LppFrame data list by type
> feat: add function LppFrame.get_by_type

- cayennelpp/lpp_frame.py
> refactor: add getter for data list

- cayennelpp/__init__.py
- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_data.py
this PR fixes (almost?) all docstrings to fix issues reported by codacy. It also piggybacks a fix for the redefined type error.
> fix: docstrings

- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
> refactor: remove logging output and imports

- README.md
> chore: update Codacy badges in README

- cayennelpp/lpp_type.py
fix an issue codacy found, some code deduplication - might also be handy when adding more data types.
> refactor: deduplicate conversion of 3D sensor data

- .travis.yml
fix is required to make tests work (again)
> chore: run flake8 only for lib code

- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
minor refinements and add missing docstrings
> docs: add and update docstrings

- README.md
- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_frame.py
- cayennelpp/tests/test_lpp_type_current.py
this PR adds support for current sensors, it also may serve as a minimal example on how to easily add new sensor types with basic tests.
> feat: Add current sensor type

- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_type.py
- cayennelpp/tests/test_lpp_type_dio.py
- cayennelpp/tests/test_lpp_type_illuminance.py
this should increase test code coverage (again)
> fix: lpp_type tests

- README.md
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
- cayennelpp/tests/test_lpp_frame.py
adds all missing LPP types to match (and actual overcome) support of  https://github.com/ElectronicCats/CayenneLPP
fixes #40
> feat: Add more types

- setup.py
- usetup.py
just update version in setup.py for next release
> chore: prepare v2.1.0

- .pydocstyle
- cayennelpp/__init__.py
- cayennelpp/lpp_data.py
- cayennelpp/lpp_frame.py
- cayennelpp/lpp_type.py
> docs: refined docstrings
